-- THIS FILE WAS AUTOMATICALLY GENERATED BY TileZed
local overlayMap = {}
overlayMap.VERSION = 1
overlayMap["Union_Pallets_01_0"] = {{ name = "other", tiles = {"Union_Filler_01_0", "Union_Filler_01_0"} }}
overlayMap["Union_Pallets_01_1"] = {{ name = "other", tiles = {"Union_Filler_01_1"} }}
overlayMap["Union_Pallets_01_2"] = {{ name = "other", tiles = {"Union_Filler_01_2"} }}
overlayMap["Union_Pallets_01_3"] = {{ name = "other", tiles = {"Union_Filler_01_3"} }}
overlayMap["Union_Pallets_01_4"] = {{ name = "other", tiles = {"Union_Filler_01_4"} }}
overlayMap["Union_Pallets_01_5"] = {{ name = "other", tiles = {"Union_Filler_01_5"} }}
overlayMap["Union_Pallets_01_6"] = {{ name = "other", tiles = {"Union_Filler_01_6"} }}
overlayMap["Union_Pallets_01_7"] = {{ name = "other", tiles = {"Union_Filler_01_7"} }}
overlayMap["Union_Pallets_01_8"] = {{ name = "other", tiles = {"Union_Filler_01_8"} }}
overlayMap["Union_Pallets_01_9"] = {{ name = "other", tiles = {"Union_Filler_01_9"} }}
overlayMap["Union_Pallets_01_10"] = {{ name = "other", tiles = {"Union_Filler_01_10", "Union_Filler_01_10"} }}
overlayMap["Union_Pallets_01_11"] = {{ name = "other", tiles = {"Union_Filler_01_11", "Union_Filler_01_11"} }}
overlayMap["Union_Pallets_01_12"] = {{ name = "other", tiles = {"Union_Filler_01_12", "Union_Filler_01_12"} }}
overlayMap["Union_Pallets_01_13"] = {{ name = "other", tiles = {"Union_Filler_01_13", "Union_Filler_01_13"} }}
overlayMap["Union_Pallets_01_14"] = {{ name = "other", tiles = {"Union_Filler_01_14", "Union_Filler_01_14"} }}
overlayMap["Union_Pallets_01_15"] = {{ name = "other", tiles = {"Union_Filler_01_15", "Union_Filler_01_15"} }}


if not TILEZED then
	getContainerOverlays():addOverlays(overlayMap)
end

return overlayMap
